version: '2'

services:
  openldap:
    image: osixia/openldap
#    command: --copy-service
    env_file:
      - ./ldap.env
#    volumes:
#      - config:/etc/ldap/slapd.d
#      - database:/var/lib/ldap
    ports:
      - 389:389

  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    links:
      - openldap
    depends_on:
      - openldap
    ports:
      - 6443:443
